// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0_qQqK0TtpVDhGU5Kuqy0na20FkVkiYs',
    appId: '1:706164682164:android:1abfce785908d7c7a7d6e1',
    messagingSenderId: '706164682164',
    projectId: 'taraqqiyot-teaching-center',
    storageBucket: 'taraqqiyot-teaching-center.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz4WKJsU3VjafI956szmXvj2xxNj0YTpU',
    appId: '1:706164682164:web:cae09c91675a54d6a7d6e1',
    messagingSenderId: '706164682164',
    projectId: 'taraqqiyot-teaching-center',
    authDomain: 'taraqqiyot-teaching-center.firebaseapp.com',
    storageBucket: 'taraqqiyot-teaching-center.firebasestorage.app',
    measurementId: 'G-BDXDFE9WYM',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2phEGC9WUi_rHqGV4a7-7ObJpyERBs9A',
    appId: '1:706164682164:ios:fb92b005d4188f04a7d6e1',
    messagingSenderId: '706164682164',
    projectId: 'taraqqiyot-teaching-center',
    storageBucket: 'taraqqiyot-teaching-center.firebasestorage.app',
    iosBundleId: 'uz.taraqqiyot.mobile',
  );
}
